version: '2.5.1'
services:
  vaccination:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8083:80
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
